server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://183.100.18.224:3306/JunBeom
    username: root
    password: swhacademy!
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-exclude: static

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect